### ISSUE TITLE
querying with fl=ack does not retrieve any content

### ISSUE THREAD

**Issue by gmella** [adsabs/solr-service#60]
I can use ack in the query but can't get ack field in output. 
ack is listed a searchable and retrievable in https://ui.adsabs.harvard.edu/help/search/comprehensive-solr-term-list

Is this a documentation or code issue ?

**Comment by tjacovich** [comment]
Hi @gmella Thank you for bringing this issue to our attention. In this particular case the documentation is what is incorrect. The `ack` section is extracted from the `fulltext` of the documents. There are restrictions on the `fulltext` of certain documents that allow us to let users query the contents, but prevent us from sharing the actual text publicly. The error should now be corrected. Please don't hesitate to reach out if you have any other questions.

Thank you again for bringing this issue to our attention and helping us to improve the quality of our documentation.
